workspace 'XLPagerTapStrip_Ex.xcworkspace'
platform :ios, '11.0'
use_frameworks!
inhibit_all_warnings!

target 'XLPagerTapStrip_Ex' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XLPagerTapStrip_Ex

  pod 'XLPagerTabStrip', '~> 9.0'
  pod 'SnapKit', '~> 5.6.0' 


  post_install do |installer|
   installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
     config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
   end
  end

end
